name:        ${project.artifactId}
version:     ${project.version}
description: ${project.description}
author:      RoyCurtis
website:     https://github.com/Gamealition/TestDummy
main:        roycurtis.testdummy.TestDummy

commands:
   testdummy:
     description: Test dummy
     aliases: [test]
     usage: /<command> <biome name>